#Blockbox settings
#Sun Jun 28 14:07:57 PDT 2026
anisotropicFiltering=true
antiAliasing=true
cloudRenderDistance=96
cloudsEnabled=true
fastMove=false
fogDensity=0.600
fov=100.000
fullscreen=false
guiScale=2
pauseEscReturnsToGame=true
renderDistance=18
smoothLighting=true
soundEnabled=true
texturePack=default
vsync=true
worldDarkening=true
